// <auto-generated />
namespace MediaMeetV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20151214173368_AddTheTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20151214173368_AddTheTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201512141805392_20151214173368_AddTheTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
